Repository josharagon/Refactor-Tractor, pull requests merged in 2021-03, with the labels that each got.

#60 Post data
  src/index.html
  src/scripts.js
Labels: Design/UI, Refactoring, enhancement, testing

#65 Feature/responsiveness
  src/css/style.scss
  src/index.html
Labels: Design/UI

#66 Post data
  src/APICalls.js
  src/PostData.js
  src/images/bed-solid.svg
  src/images/tint-solid.svg
  src/images/walking-solid.svg
  src/scripts.js
Labels: enhancement

#71 Refactor functions
  src/PostData.js
  src/User-repo.js
  src/index.html
  src/scripts.js
Labels: Refactoring
